### ISSUE TITLE
Pipeline component 'mfd_tokenizer' returned <class 'list'> instead of a Doc. If you're using a custom component, maybe you forgot to return the processed Doc?

### ISSUE THREAD

**Issue by uless** [medianeuroscience/emfdscore#14]
We were attempting to run emfd (as in the tutorial) today but this error code kept popping up in the final stage of scoring documents.

/usr/local/lib/python3.7/dist-packages/spacy/language.py:1899: UserWarning: [W123] Argument disable with value ['ner', 'parser'] is used instead of ['senter'] as specified in the config. Be aware that this might affect other components in your pipeline.
  config_value=config["nlp"][key],
Processed: 499 100% |❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤❤| Elapsed Time: 0:00:00 ETA:  00:00:00
ValueError                                Traceback (most recent call last)
[<ipython-input-30-6c7af4835ab2>](https://localhost:8080/#) in <module>
      9 OUT_CSV_PATH = 'all-sent.csv'
     10 
---> 11 df = score_docs(template_input,DICT_TYPE,PROB_MAP,SCORE_METHOD,OUT_METRICS,num_docs)
     12 df.to_csv(OUT_CSV_PATH, index=False)

1 frames
[/usr/local/lib/python3.7/dist-packages/spacy/language.py](https://localhost:8080/#) in __call__(self, text, disable, component_cfg)
   1031                 error_handler(name, proc, [doc], e)
   1032             if not isinstance(doc, Doc):
-> 1033                 raise ValueError(Errors.E005.format(name=name, returned_type=type(doc)))
   1034         return doc
   1035 

ValueError: [E005] Pipeline component 'mfd_tokenizer' returned <class 'list'> instead of a Doc. If you're using a custom component, maybe you forgot to return the processed Doc?

We 

- used the default code presented in the tutorial, 
- with the template csv file provided here, and 
- restarted environment & reinstalled the packages several times, 
- tried in different systems (linux, win, os, colab)

But this error message kept the same.

It seems that the scoring steps do not accept the tokenized result from mfd_tokenizer anymore. We wonder if there're further updates on the relying packages like SpaCy recently to keep us from successfully run emfd on the demo document.

**Comment by uless** [comment]
Solved by ourselves. Solution:

1. Uninstall SpaCy (was 3.4.2)
2. Install Spacy 3.4.0
3. All good.

**Comment by fhopp** [comment]
Great; we may need to do some refactoring or specify the spacy version during install.

**Comment by szaken** [comment]
I tried to do just that, but it doesn't seem that the package is available (including in anaconda)? Are there other ways around this?

**Comment by naomicustodio677** [comment]
@uless @fhopp this workaround didn't work for. I have the same error both with space 3.4.0 and 3.5.2 (latest version), any ideas on how to solve it?

**ValueError: [E005] Pipeline component 'mfd_tokenizer' returned  instead of a Doc. If you're using a custom component, maybe you forgot to return the processed Doc?**

**Comment by uless** [comment]
@naomicustodio677 eMFD package has a relatively harsh requirement for data format therefore you might want to check it before proceed...
I wrote these tricks (in part 2) for wrangling your data for a smooth input into emfd:
https://colab.research.google.com/drive/1iiIuw6I9S7FMzejyPSsCQQ3SsUPO3_r1?usp=sharing

**Comment by shz126** [comment]
Hello @uless @fhopp @naomicustodio677,

I am using the eMFD  to analyze some tweets.

When I ran "%%bash
emfdscore sampled_tweets_all_without.csv all-sent.csv bow emfd all sentiment" in jupyter notebook, I obtained 
"Traceback (most recent call last):
  File "C:\Users\authuser.PITT\.conda\envs\emfd\Scripts\emfdscore", line 67, in <module>
    df = score_docs(csv,DICT_TYPE,PROB_MAP,SCORE_METHOD,OUT_METRICS,num_docs)
  File "C:\Users\authuser.PITT\.conda\envs\emfd\lib\site-packages\emfdscore\scoring.py", line 359, in score_docs
    scored_docs.append(nlp(row))
  File "C:\Users\authuser.PITT\AppData\Roaming\Python\Python39\site-packages\spacy\language.py", line 1059, in __call__
    raise ValueError(Errors.E005.format(name=name, returned_type=type(doc)))
ValueError: [E005] Pipeline component 'mfd_tokenizer' returned <class 'list'> instead of a Doc. If you're using a custom component, maybe you forgot to return the processed Doc?
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[29], line 1
----> 1 get_ipython().run_cell_magic('bash', '', 'emfdscore sampled_tweets_all_without.csv all-sent.csv bow emfd all sentiment\n')

File ~\.conda\envs\emfd\lib\site-packages\IPython\core\interactiveshell.py:2517, in InteractiveShell.run_cell_magic(self, magic_name, line, cell)
   2515 with self.builtin_trap:
   2516     args = (magic_arg_s, cell)
-> 2517     result = fn(*args, **kwargs)
   2519 # The code below prevents the output from being displayed
   2520 # when using magics with decorator @output_can_be_silenced
   2521 # when the last Python token in the expression is a ';'.
   2522 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File ~\.conda\envs\emfd\lib\site-packages\IPython\core\magics\script.py:154, in ScriptMagics._make_script_magic.<locals>.named_script_magic(line, cell)
    152 else:
    153     line = script
--> 154 return self.shebang(line, cell)

File ~\.conda\envs\emfd\lib\site-packages\IPython\core\magics\script.py:314, in ScriptMagics.shebang(self, line, cell)
    309 if args.raise_error and p.returncode != 0:
    310     # If we get here and p.returncode is still None, we must have
    311     # killed it but not yet seen its return code. We don't wait for it,
    312     # in case it's stuck in uninterruptible sleep. -9 = SIGKILL
    313     rc = p.returncode or -9
--> 314     raise CalledProcessError(rc, cell)

CalledProcessError: Command 'b'emfdscore sampled_tweets_all_without.csv all-sent.csv bow emfd all sentiment\n'' returned non-zero exit status 1."

To deal with this problem, I have tried the following:
1. Check the mfd_tokenizer function in the emfdscore package to ensure it is returning a SpaCy Doc object. Modify the function if necessary to ensure compliance with SpaCy's pipeline requirements.

2. Check if there's an updated version of the emfdscore package that resolves this issue. Update the package using: bash
pip install --upgrade emfdscore

3. Add debugging statements inside the scoring.py file (if editable) to inspect the output of the mfd_tokenizer function. Ensure it transforms input correctly into a Doc object.

4. My system already has Git Bash, and I ensure it has the necessary permissions and that the paths are set correctly. Use Git Bash to directly invoke the script: bash
"C:/Program Files/Git/bin/bash.exe" -c "python path/to/emfdscore.py args"

5. Check if the sampled_tweets_all_without.csv file is properly formatted and readable by emfdscore. Ensure there are no invalid characters or unexpected formats that might cause issues during processing.

6. I override the mfd_tokenizer in the pipeline with a custom tokenizer that correctly returns a Doc object.  More specifically, I use the codes like:
import spacy
from spacy.tokens import Doc
from spacy.language import Language

@Language.component("mfd_tokenizer")
def mfd_tokenizer(doc):
    tokens = [token.text for token in doc]
    return Doc(doc.vocab, words=tokens)

nlp = spacy.load("en_core_web_sm", disable=['ner', 'parser'])
nlp.add_pipe("mfd_tokenizer", first=True)

and 
import spacy

def custom_tokenizer(doc):
    return nlp.make_doc(doc.text)

nlp = spacy.load("en_core_web_sm")
nlp.replace_pipe("mfd_tokenizer", custom_tokenizer)

7. Inspect Input and Component Behavior: Run the component on a small sample dataset to isolate the error:
For instance, I try the codes:
from emfdscore.scoring import mfd_tokenizer
doc = nlp("Sample text for testing.")
print(mfd_tokenizer(doc))

The outcome is
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[26], line 1
----> 1 from emfdscore.scoring import mfd_tokenizer
      2 doc = nlp("Sample text for testing.")
      3 print(mfd_tokenizer(doc))

ImportError: cannot import name 'mfd_tokenizer' from 'emfdscore.scoring' (C:\Users\authuser.PITT\.conda\envs\emfd\lib\site-packages\emfdscore\scoring.py)

8. Installation of Spacy 3.4.0 provided by @uless

All of these methods have failed.  Hence, could you please tell me how I can deal with this problem?

Thanks very much for all your help!
