### ISSUE TITLE
Issue in (base) $ python -m spacy download en_core_web_sm

### ISSUE THREAD

**Issue by herjccc** [medianeuroscience/emfdscore#22]
Hi, I set my python using this codes. 

(base) $ python -m spacy download en_core_web_sm
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/herjc/lda-2/lib/python3.8/site-packages/spacy/__init__.py", line 13, in <module>
    from . import pipeline  # noqa: F401
  File "/Users/herjc/lda-2/lib/python3.8/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/Users/herjc/lda-2/lib/python3.8/site-packages/spacy/pipeline/attributeruler.py", line 8, in <module>
    from ..language import Language
  File "/Users/herjc/lda-2/lib/python3.8/site-packages/spacy/language.py", line 43, in <module>
    from .pipe_analysis import analyze_pipes, print_pipe_analysis, validate_attrs
  File "/Users/herjc/lda-2/lib/python3.8/site-packages/spacy/pipe_analysis.py", line 6, in <module>
    from .tokens import Doc, Span, Token
  File "/Users/herjc/lda-2/lib/python3.8/site-packages/spacy/tokens/__init__.py", line 1, in <module>
    from ._serialize import DocBin
  File "/Users/herjc/lda-2/lib/python3.8/site-packages/spacy/tokens/_serialize.py", line 14, in <module>
    from ..vocab import Vocab
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "spacy/tokens/doc.pyx", line 49, in init spacy.tokens.doc
  File "/Users/herjc/lda-2/lib/python3.8/site-packages/spacy/schemas.py", line 287, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 634, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)

And I got a error here
**TypeError: issubclass() arg 1 must be a class**

**Comment by patrickvankessel** [comment]
Having the same problem; seems to be outdated code that's incompatible with newer versions of Spacy. I'll throw together and PR a fix after the holidays if no one gets to it before then, not sure how actively the creators maintain this library anymore.
