### ISSUE TITLE
ValueError: [E005] Pipeline component 'mfd_tokenizer' returned <class 'list'> instead of a Doc. If you're using a custom component, maybe you forgot to return the processed Doc?

### ISSUE THREAD

**Issue by shz126** [medianeuroscience/emfdscore#28]
Hello everyone,

I am using the eMFD to analyze some tweets.

When I ran "%%bash
emfdscore sampled_tweets_all_without.csv all-sent.csv bow emfd all sentiment" in jupyter notebook, I obtained
"Traceback (most recent call last):
File "C:\Users\authuser.PITT.conda\envs\emfd\Scripts\emfdscore", line 67, in
df = score_docs(csv,DICT_TYPE,PROB_MAP,SCORE_METHOD,OUT_METRICS,num_docs)
File "C:\Users\authuser.PITT.conda\envs\emfd\lib\site-packages\emfdscore\scoring.py", line 359, in score_docs
scored_docs.append(nlp(row))
File "C:\Users\authuser.PITT\AppData\Roaming\Python\Python39\site-packages\spacy\language.py", line 1059, in call
raise ValueError(Errors.E005.format(name=name, returned_type=type(doc)))
ValueError: [E005] Pipeline component 'mfd_tokenizer' returned <class 'list'> instead of a Doc. If you're using a custom component, maybe you forgot to return the processed Doc?
CalledProcessError Traceback (most recent call last)
Cell In[29], line 1
----> 1 get_ipython().run_cell_magic('bash', '', 'emfdscore sampled_tweets_all_without.csv all-sent.csv bow emfd all sentiment\n')

File ~.conda\envs\emfd\lib\site-packages\IPython\core\interactiveshell.py:2517, in InteractiveShell.run_cell_magic(self, magic_name, line, cell)
2515 with self.builtin_trap:
2516 args = (magic_arg_s, cell)
-> 2517 result = fn(*args, **kwargs)
2519 # The code below prevents the output from being displayed
2520 # when using magics with decorator @output_can_be_silenced
2521 # when the last Python token in the expression is a ';'.
2522 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File ~.conda\envs\emfd\lib\site-packages\IPython\core\magics\script.py:154, in ScriptMagics._make_script_magic..named_script_magic(line, cell)
152 else:
153 line = script
--> 154 return self.shebang(line, cell)

File ~.conda\envs\emfd\lib\site-packages\IPython\core\magics\script.py:314, in ScriptMagics.shebang(self, line, cell)
309 if args.raise_error and p.returncode != 0:
310 # If we get here and p.returncode is still None, we must have
311 # killed it but not yet seen its return code. We don't wait for it,
312 # in case it's stuck in uninterruptible sleep. -9 = SIGKILL
313 rc = p.returncode or -9
--> 314 raise CalledProcessError(rc, cell)

CalledProcessError: Command 'b'emfdscore sampled_tweets_all_without.csv all-sent.csv bow emfd all sentiment\n'' returned non-zero exit status 1."

To deal with this problem, I have tried the following:

Check the mfd_tokenizer function in the emfdscore package to ensure it is returning a SpaCy Doc object. Modify the function if necessary to ensure compliance with SpaCy's pipeline requirements.

Check if there's an updated version of the emfdscore package that resolves this issue. Update the package using: bash
pip install --upgrade emfdscore

Add debugging statements inside the scoring.py file (if editable) to inspect the output of the mfd_tokenizer function. Ensure it transforms input correctly into a Doc object.

My system already has Git Bash, and I ensure it has the necessary permissions and that the paths are set correctly. Use Git Bash to directly invoke the script: bash
"C:/Program Files/Git/bin/bash.exe" -c "python path/to/emfdscore.py args"

Check if the sampled_tweets_all_without.csv file is properly formatted and readable by emfdscore. Ensure there are no invalid characters or unexpected formats that might cause issues during processing.

I override the mfd_tokenizer in the pipeline with a custom tokenizer that correctly returns a Doc object. More specifically, I use the codes like:
import spacy
from spacy.tokens import Doc
from spacy.language import Language

@Language.component("mfd_tokenizer")
def mfd_tokenizer(doc):
tokens = [token.text for token in doc]
return Doc(doc.vocab, words=tokens)

nlp = spacy.load("en_core_web_sm", disable=['ner', 'parser'])
nlp.add_pipe("mfd_tokenizer", first=True)

and
import spacy

def custom_tokenizer(doc):
return nlp.make_doc(doc.text)

nlp = spacy.load("en_core_web_sm")
nlp.replace_pipe("mfd_tokenizer", custom_tokenizer)

Inspect Input and Component Behavior: Run the component on a small sample dataset to isolate the error:
For instance, I try the codes:
from emfdscore.scoring import mfd_tokenizer
doc = nlp("Sample text for testing.")
print(mfd_tokenizer(doc))
The outcome is
ImportError Traceback (most recent call last)
Cell In[26], line 1
----> 1 from emfdscore.scoring import mfd_tokenizer
2 doc = nlp("Sample text for testing.")
3 print(mfd_tokenizer(doc))

ImportError: cannot import name 'mfd_tokenizer' from 'emfdscore.scoring' (C:\Users\authuser.PITT.conda\envs\emfd\lib\site-packages\emfdscore\scoring.py)

Installation of Spacy 3.4.0 provided by @uless

All of these methods have failed. Hence, could you please tell me how I can deal with this problem?

Thanks very much for all your help!

**Comment by lucasjwiese** [comment]
Hi, I was encountering the same problem but have a fix.

Take a look at my fork: https://github.com/lucasjwiese/emfdscore
And I have created a Pull Request for a fix from the authors: https://github.com/medianeuroscience/emfdscore/pull/30

Hopefully they can get to this and update the main package.

Hope this helps for now.

**Comment by shz126** [comment]
Hello Lucas @lucasjwiese ,

I used your codes in scoring.py from https://github.com/medianeuroscience/emfdscore/pull/30/commits/c597f8750902c1bbd22a9b2de76605b25d6a50f5 and met a new problem of obtaining 
"Traceback (most recent call last): File "C:\Users\authuser.PITT.000\.conda\envs\emfd\Scripts\emfdscore.py", line 7, in <module> from emfdscore.scoring import score_docs, pat_docs File "C:\Users\authuser.PITT.000\.conda\envs\emfd\Scripts\emfdscore.py", line 7, in <module> from emfdscore.scoring import score_docs, pat_docs ModuleNotFoundError: No module named 'emfdscore.scoring'; 'emfdscore' is not a package" 

after running codes 

"!C:\Users\authuser.PITT.000\.conda\envs\emfd\python.exe "C:\Users\authuser.PITT.000\.conda\envs\emfd\Scripts\emfdscore.py" sampled_tweets_all_without.csv all-sent.csv bow emfd all sentiment" in jupyter notebook.

How can I deal with it? 

If I do not add a .py extension to the file of emfdscore in C:\Users\authuser.PITT.000\.conda\envs\emfd\Scripts\, I will obtain 
"'C:\Users\authuser.PITT.000\.conda\envs\emfd\Scripts\emfdscore' is not recognized as an internal or external command,
operable program or batch file."

after running codes 

"!C:\Users\authuser.PITT.000\.conda\envs\emfd\Scripts\emfdscore sampled_tweets_all_without.csv all-sent.csv bow emfd all sentiment".

Now it looks like running the program emfdscore itself becomes a problem.  How did you accomplish the equivalent of this Command Line "%%bash
emfdscore emfdscore/template_input.csv all-sent.csv bow emfd all sentiment" on your computer?

Thanks very much for your help!

**Comment by lucasjwiese** [comment]
Hi @shz126,

Glad you tried, and sorry to hear that there are more errors! Let me preface with two things here: (1) I don't have much experience with Conda environments and so might not know how file structures in Conda should look, and (2) I ran all the emfdscore functionality from my own python script. So, never dealt with command line to begin with after I installed 'emfdscore'.

It looks like it could be a problem with your environment variables set up. Meaning, you mind need to direct Windows to understand what "emfdscore" is when you run it in the directory with your data, and not with the scoring script. You can find plenty of sources for how to set an environment variable online!

It looks like it might also look like you might not need the full "!C:\Users\authuser.PITT.000.conda\envs\emfd\Scripts\emfdscore" preface to the command line. Have you tried just '`emfdscore [data].csv bow emfd all sentiment`'? 

I'd also recommend looking whether 'emfdscore' is installed properly. I never went through Conda, and just ran "`pip install https://github.com/medianeuroscience/emfdscore/archive/master.zip`". From here, I had a Python package like any other. I imported it to my script via '`from emfdscore.scoring import score_docs`'. Then ran the function in my code like:

```
eMFD_scores = score_docs(
            long_stories,  # input
            DICT_TYPE,  # dictionary type
            PROB_MAP,  # current prob map iteration
            SCORE_METHOD,  # scoring method
            out,  # current out metric iteration
            num_docs  # num documents to score
        )
```

So, perhaps try to just uninstall emfdscore package, reinstall it, and edit only the 'scoring.py' file when the package is installed to your machine. For me, it installs to the following directory: "`C:\Users\[user]\AppData\Local\Programs\Python\Python311\Lib\site-packages\emfdscore`" So -- in this directory I have a number of files, but particularly 'scoring.py' which I edited and saved. 

You can also try uninstalling the emfdscore and reinstalling my GitHub fork directory. I would think this should work pretty reliably, since it is a direct mirror aside from my fixes. To install a python package from a GitHub fork, the command for this, in your command line / terminal, is: `pip install git+https://github.com/lucasjwiese/emfdscore.git@master`. From there, you should have a python package installed to your typical Python Site Packages. Meaning, you can open up the directory where your data is and run '`emfdscore [data].csv .... .... ....`' or create a Python script yourself and import it as a normal function.

Hopefully I didn't misunderstand the errors you had here, and hopefully some of this makes sense. If something doesn't make sense, let me know and maybe I can help troubleshoot further.

Thanks
Lucas

**Comment by shz126** [comment]
Hello Lucas @lucasjwiese ,

Great, thanks so much for your sharing!

I used the Conda environment according to the official guideline of eMFDscore from https://github.com/lucasjwiese/emfdscore.

I will try to solve the problem that I am having based on your very helpful information and suggestions and share the progress with you instantly.

Best wishes.
 
Sincerely yours,
 
Shuli Zhang

**Comment by shz126** [comment]
Hello Lucas @lucasjwiese ,

I solved the problem by running emfdscore without Conda environments.

Hence, the official guideline of eMFDscore is misleading and the Conda environment is not necessary to run emfdscore.

Perhaps you could also tell the authors of emfdscore about this, so that they can add the relevant tip to the instructions for emfdscore.

Thanks very much for your helpful advice again!

Best wishes.

Sincerely yours,

Shuli Zhang

**Comment by lucasjwiese** [comment]
Hi @shz126,

Excellent to hear that it worked for you. Good luck with your project!
